# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
  - name: golang
    args: ['go', 'build', '.']

images:
  - 'gcr.io/$PROJECT_ID/docker-compose:latest'
  - 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
tags: ['cloud-builders-community']